/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Hora;
import javax.swing.JOptionPane;

/**
 *
 * @author SERVIDOR
 */
public class Princiapal7 extends javax.swing.JFrame {

    /**
     * Creates new form Princiapal7
     */
    Hora h;
    public Princiapal7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSegundos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        txtMinutos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoraDos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMinutosDos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSegundosDos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdValidarHora = new javax.swing.JButton();
        cmdMenor = new javax.swing.JButton();
        cmdMayor = new javax.swing.JButton();
        cmdIguales = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("HORAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        txtSegundos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundosKeyTyped(evt);
            }
        });
        jPanel1.add(txtSegundos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 60, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText(":");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 10, 30));

        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoraKeyTyped(evt);
            }
        });
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 40));

        txtMinutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinutosKeyTyped(evt);
            }
        });
        jPanel1.add(txtMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 60, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText(":");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 10, 30));

        txtHoraDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoraDosKeyTyped(evt);
            }
        });
        jPanel1.add(txtHoraDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 60, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText(":");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 10, 30));

        txtMinutosDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinutosDosKeyTyped(evt);
            }
        });
        jPanel1.add(txtMinutosDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 60, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText(":");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 10, 30));

        txtSegundosDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundosDosKeyTyped(evt);
            }
        });
        jPanel1.add(txtSegundosDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 60, 40));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setBackground(new java.awt.Color(153, 255, 153));
        cmdCrear.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 40));

        cmdValidarHora.setBackground(new java.awt.Color(153, 255, 153));
        cmdValidarHora.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdValidarHora.setText("Validar Hora ");
        cmdValidarHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdValidarHoraActionPerformed(evt);
            }
        });
        jPanel2.add(cmdValidarHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 140, 40));

        cmdMenor.setBackground(new java.awt.Color(153, 255, 153));
        cmdMenor.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdMenor.setText("Hora Menor");
        cmdMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMenorActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 40));

        cmdMayor.setBackground(new java.awt.Color(153, 255, 153));
        cmdMayor.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdMayor.setText("Hora Mayor");
        cmdMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMayorActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 40));

        cmdIguales.setBackground(new java.awt.Color(153, 255, 153));
        cmdIguales.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdIguales.setText("Horas iguales");
        cmdIguales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIgualesActionPerformed(evt);
            }
        });
        jPanel2.add(cmdIguales, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 130, 40));

        cmdMostrar.setBackground(new java.awt.Color(153, 255, 153));
        cmdMostrar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 100, 40));

        cmdBorrar.setBackground(new java.awt.Color(153, 255, 153));
        cmdBorrar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 310, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int hora,minutos,segundos,hora2,minutos2,segundos2;
        
        if (txtHora.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Digite por favor la primera hora","Error",JOptionPane.ERROR_MESSAGE);
         txtHora.requestFocusInWindow();
        }else if (txtMinutos.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog (this,"Digite por favor los minutos de la primera hora","Error",JOptionPane.ERROR_MESSAGE);
         txtMinutos.requestFocusInWindow();
        }else if (txtSegundos.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(this, "Digite por favor los segundos de la primera hora", "Error", JOptionPane.ERROR_MESSAGE);
          txtSegundos.requestFocusInWindow();     
        }else if (txtHoraDos.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Digite por favor la segunda hora","Error",JOptionPane.ERROR_MESSAGE);
           txtHoraDos.requestFocusInWindow();
        }else if (txtMinutosDos.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog (this,"Digite por favor los minutos de la segunda hora","Error",JOptionPane.ERROR_MESSAGE);
         txtMinutosDos.requestFocusInWindow();
         
        }else if (txtSegundosDos.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(this, "Digite por favor los segundos de la segunda hora", "Error", JOptionPane.ERROR_MESSAGE);
          txtSegundos.requestFocusInWindow();
        
        }else{
            hora=Integer.parseInt(txtHora.getText());
            minutos=Integer.parseInt (txtMinutos.getText());
            segundos=Integer.parseInt (txtSegundos.getText());
            hora2=Integer.parseInt(txtHoraDos.getText());
            minutos2=Integer.parseInt(txtMinutosDos.getText());
            segundos2=Integer.parseInt(txtSegundosDos.getText());
            
            h = new Hora (hora2,minutos2,segundos2);
            JOptionPane.showMessageDialog(this, "Su hora ha sido creada");
        }   
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdValidarHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdValidarHoraActionPerformed
        int hora,minutos,segundos;
        String vald;
        hora=Integer.parseInt(txtHora.getText());
        minutos=Integer.parseInt (txtMinutos.getText());
        segundos=Integer.parseInt (txtSegundos.getText());
        vald=h.validar();
        JOptionPane.showMessageDialog(this, vald);
      
    }//GEN-LAST:event_cmdValidarHoraActionPerformed

    private void cmdMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMenorActionPerformed
        int hora,minutos,segundos,hora2,minutos2,segundos2;
        String menor;
        hora=Integer.parseInt(txtHora.getText());
        minutos=Integer.parseInt (txtMinutos.getText());
        segundos=Integer.parseInt (txtSegundos.getText());
        hora2=Integer.parseInt(txtHoraDos.getText());
        minutos2=Integer.parseInt (txtMinutosDos.getText());
        segundos2=Integer.parseInt(txtSegundosDos.getText());
        
        menor=h.menor(hora2, minutos2, segundos2);
        JOptionPane.showMessageDialog(this, menor);
        
    }//GEN-LAST:event_cmdMenorActionPerformed

    private void cmdIgualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIgualesActionPerformed
        int hora,minutos,segundos,hora2,minutos2,segundos2;
        String ig;
        hora=Integer.parseInt(txtHora.getText());
        minutos=Integer.parseInt (txtMinutos.getText());
        segundos=Integer.parseInt (txtSegundos.getText());
        hora2=Integer.parseInt(txtHoraDos.getText());
        minutos2=Integer.parseInt(txtMinutosDos.getText());
        segundos2=Integer.parseInt(txtSegundosDos.getText());
        
        ig=h.igual(hora2, minutos2, segundos2);
        JOptionPane.showMessageDialog (this, ig);
    }//GEN-LAST:event_cmdIgualesActionPerformed

    private void cmdMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMayorActionPerformed
        int hora,minutos,segundos,hora2,minutos2,segundos2;
        String mayor;
        hora=Integer.parseInt(txtHora.getText());
        minutos=Integer.parseInt (txtMinutos.getText());
        segundos=Integer.parseInt (txtSegundos.getText());
        hora2=Integer.parseInt(txtHoraDos.getText());
        minutos2=Integer.parseInt (txtMinutosDos.getText());
        segundos2=Integer.parseInt(txtSegundosDos.getText());
        mayor=h.mayor(hora2, minutos2, segundos2);
        JOptionPane.showMessageDialog(this, mayor);
    }//GEN-LAST:event_cmdMayorActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        int hora,minutos,segundos;
        String mos;
        hora=Integer.parseInt(txtHora.getText());
        minutos=Integer.parseInt (txtMinutos.getText());
        segundos=Integer.parseInt(txtSegundos.getText());
        mos=h.mostrar();
        JOptionPane.showMessageDialog(this, mos);
        
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
       txtHora.setText("");
       txtHoraDos.setText("");
       txtMinutos.setText("");
       txtMinutosDos.setText("");
       txtSegundos.setText("");
       txtSegundosDos.setText("");
       
       
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyTyped
       char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtHoraKeyTyped

    private void txtMinutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinutosKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtMinutosKeyTyped

    private void txtSegundosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundosKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtSegundosKeyTyped

    private void txtHoraDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraDosKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtHoraDosKeyTyped

    private void txtMinutosDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinutosDosKeyTyped
       char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtMinutosDosKeyTyped

    private void txtSegundosDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundosDosKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtSegundosDosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Princiapal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Princiapal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Princiapal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Princiapal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Princiapal7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdIguales;
    private javax.swing.JButton cmdMayor;
    private javax.swing.JButton cmdMenor;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdValidarHora;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtHoraDos;
    private javax.swing.JTextField txtMinutos;
    private javax.swing.JTextField txtMinutosDos;
    private javax.swing.JTextField txtSegundos;
    private javax.swing.JTextField txtSegundosDos;
    // End of variables declaration//GEN-END:variables
}
